version: '3.5'

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    hostname: nzbget.server
    ports:
      - 6789
    volumes:
      - /serverapps/nzbget/config:/config
      - /serverapps/nzbget:/downloads
      - /downloads:/completed
    environment:
      TZ: _timezone_
      PUID: _nzbgetuid_
      PGID: _nzbgetgid_
    restart: unless-stopped
    networks:
      - downloader

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    hostname: sonarr.server
    ports:
      - 8989
      - 9898
    volumes:
      - /serverapps/sonarr/config:/config
      - /dvr/tv:/tv
      - /downloads:/downloads
    environment:
      PUID: _sonarruid_
      PGID: _sonarrgid_
      TZ: _timezone_
      UMASK_SET: 022
    restart: unless-stopped
    networks:
      - downloader

networks:
  downloader:
    name: _downloadernetwork_
