version: '3.5'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex.server
    ports:
      - "127.0.0.1:32400:32400/tcp"
      - "127.0.0.1:3005:3005/tcp" 
      - "127.0.0.1:8324:8324/tcp" 
      - "127.0.0.1:32469:32469/tcp" 
      - "127.0.0.1:1900:1900/udp" 
      - "127.0.0.1:32410:32410/udp" 
      - "127.0.0.1:32412:32412/udp" 
      - "127.0.0.1:32413:32413/udp" 
      - "127.0.0.1:32414:32414/udp" 
    volumes:
      - /serverapps/plex/config:/config 
      - /serverapps/plex/transcode:/transcode
      - /dvr/tv:/data/tv 
      - /dvr/movies:/data/movies
    environment:
      TZ: _timezone_
      PLEX_CLAIM: _plexclaim_
      PLEX_UID: _plexuid_
      PLEX_GID: _plexgid_
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: _medianetwork_
