version: '3.5'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex.server
    ports:
      - 32400/tcp
      - 3005/tcp 
      - 8324/tcp 
      - 32469/tcp 
      - 1900/udp 
      - 32410/udp 
      - 32412/udp 
      - 32413/udp 
      - 32414/udp 
    volumes:
      - /serverapps/plex/config:/config 
      - /serverapps/plex/transcode:/transcode
      - /dvr/tv:/data/tv 
      - /dvr/movies:/data/movies
    environment:
      TZ: _timezone_
      PLEX_CLAIM: _plexclaim_
      PLEX_UID: _plexuid_
      PLEX_GID: _plexgid_
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    name: _medianetwork_
