version: '3.5'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex.server
    ports:
      - "127.0.0.1:1900:1900/udp" 
      - "127.0.0.1:3005:3005/tcp" 
      - "127.0.0.1:8324:8324/tcp" 
      - "127.0.0.1:32400:32400/tcp"
      - "127.0.0.1:32410:32410/udp" 
      - "127.0.0.1:32412-32414:32412-32414/udp" 
      - "127.0.0.1:32469:32469/tcp" 
    volumes:
      - /usr/mediaserver/plex/config:/config 
      - /usr/mediaserver/plex/transcode:/transcode
      - _tv_:/data/tv 
      - _movies_:/data/movies
      - _web_:/data/web
    environment:
      TZ: _timezone_
      PLEX_CLAIM: _plexclaim_
      PLEX_UID: _plexuid_
      PLEX_GID: _plexgid_
    restart: "no"
    networks:
      - media

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    hostname: nzbget.server
    ports:
      - "127.0.0.1:6789:6789"
    volumes:
      - /usr/mediaserver/nzbget/config:/config
      - _downloads_dir_:/downloads
      - _downloads_complete_:/completed
    environment:
      TZ: _timezone_
      PUID: _nzbgetuid_
      PGID: _nzbgetgid_
    restart: "no"
    networks:
      - downloader

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    hostname: sonarr.server
    ports:
      - "127.0.0.1:8989:8989"
      - "127.0.0.1:9898:9898"
    volumes:
      - /usr/mediaserver/sonarr/config:/config
      - _tv_:/tv
      - _downloads_dir_:/downloads
    environment:
      PUID: _sonarruid_
      PGID: _sonarrgid_
      TZ: _timezone_
      UMASK_SET: 022
    restart: "no"
    networks:
      - downloader

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    hostname: radarr:server
    environment:
      PUID: _radarruid_
      PGID: _radarrgid_
      TZ: _timezone_
    volumes:
      - /usr/mediaserver/radarr/config:/config
      - _movies_:/movies #optional
      - _downloads_dir_:/downloads #optional
    ports:
      - "127.0.0.1:7878:7878"
    restart: "no"
    networks:
      - downloader

  
networks:
  media:
    name: _medianetwork_
  downloader:
    name: _downloadernetwork_
